######################## default configuration ####################
baseURL = "https://hugoabernier.github.io/blog/"
languageCode = "en-us"
title = "Tahoe Ninjas"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "Speaking"
  URL = "speaking"
  weight = 4
  
    [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


  [[menu.footer]]
  name = "Speaking"
  URL = "speaking"
  weight = 4
  
#################### default parameters ################################
[params]

home = "Home"
# Meta data
description = "Discover the ancient art of SharePointjutsu"
author = "Hugo Bernier"
# Google Analitycs
googleAnalitycsID = "320775101"
clarityProjectID = "ci586abdwh"

# copyright
copyright = " &copy; Copyright 2022, Hugo Bernier"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "I'm not using newsletters"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################

[[params.social]]
title = "Twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/bernierh"

[[params.social]]
title = "GitHub"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/hugoabernier"

[[params.social]]
title = "LinkedIn"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/bernierh/"
